### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by Rackover**
with caching and shit!

### CODE REVIEW

**Comment by Rackover** [comment]
(do not merge yet)

**Comment by diamante0018** [comment]
how not merge?

**Comment by Rackover** [comment]
i know right 
It's almost ready i promise. tonight i fix

**Comment by Rackover** [comment]
good. don't look deeper please.

**Comment by diamante0018** [comment]
roger roger. I mean, the things I noticed look like an improvement to me.

**Comment by Rackover** [comment]
It's good to go, i will merge whenever it builds

**Pull request merged**
